def job = currentBuild.rawBuild.getParent()
def source = job.getParent().getSCMSources()[0]
def repoName = source.tokenize('/').last().replace('.git', '')
def repoBranch = BRANCH_NAME

node("general-pipeline") {
  container("ubuntu") {
    stage("Check variable") {
      echo "repoName: ${repoName}"
      echo "repoBranch: ${repoBranch}"
    }
  }
}