pipelineConfigs:
  projectConfigs:
    cpp-api-query-multiple-timezone:
      helmName: "get-time-api"
      dockerRegistry: "cpp-api-query-multiple-timezone"

    nodejs-query-multiple-timezone-gui:
      helmName: "get-time-web"
      dockerRegistry: "nodejs-query-multiple-timezone-gui"

  branchConfigs:
    main:
      dockerTag: "latest"
      namespace: "default"
    uat:
      dockerTag: "uat"
      namespace: "uat"
    dev:
      dockerTag: "dev"
      namespace: "dev"