replicaCount: 1

image:
  repository: careromspersonal/stupid-cpp-terminal-clock
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

service:
  enabled: true
  port: 80
  targetPort: 3333

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
