nameOverride: "get-time"

replicaCount: 1

image:
  repository: careromspersonal/cpp-api-query-multiple-timezone
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

service:
  enabled: true
  port: 80
  targetPort: 3333

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
