replicaCount: 1

image:
  repository: careromspersonal/stupid-cpp-sheep-counting
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

service:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
