def buildStepSelected = BUILD_STEP_SELECT.toLowerCase().replace(" ", "")
def gitRepo = ""

switch(SELECT_STUPID_PROJECT) {
  case "terminal-clock":
    gitRepo = "careroms-personal/stupid-cpp-terminal-clock.git"
  case "sheep-counting"
    gitRepo = "careroms-personal/stupid-cpp-sheep-couting.git"
  break
}

node("image-builder") {
  container("kaniko"){
    stage("Build image") {
      if(buildStepSelected.contains("builddocker")) {
        sh """
          mkdir -p /kaniko/.docker
          echo "$PODMAN_AUTH" > /kaniko/.docker/config.json

          /kaniko/executor \
            --context=git://github.com/${gitRepo}#refs/heads/main \
            --dockerfile=Dockerfile \
            --destination=careromspersonal/stupid-cpp-terminal-clock:latest
        """
      } else {
        echo "Skip docker build step."
      }
    }
  }
}

node("helm-deploy") {
  container("helm") {
    if(buildStepSelected.contains("helmdeploy")) {
      stage("Checkout Project helm file") {
        checkout(
          scmGit(
            branches: [[name: '*/main']], 
            extensions: [
              cloneOption(depth: 1, noTags: false, reference: '', shallow: true), 
              sparseCheckout([[path: 'helm']])], 
            userRemoteConfigs: [[url: "https://github.com/${gitRepo}"]]))
      }

      stage("Check file") {
        sh "ls"
      }

      stage("Helm deploy") {
        sh "helm upgrade sctc --install --namespace default ./helm --debug"
      }
    } else {
      echo "Skip Helm deploy step."
    }
  }
}