node("image-builder") {
  container("kaniko"){
    stage("Build image") {
      sh '''
        mkdir -p /kaniko/.docker
        echo "$PODMAN_AUTH" > /kaniko/.docker/config.json

        /kaniko/executor \
          --context=git://github.com/careroms-personal/stupid-cpp-hello-world.git#refs/heads/main \
          --dockerfile=Dockerfile \
          --destination=careromspersonal/hell-world-cpp:latest
      '''
    }
  }
}