def buildStepSelected = BUILD_STEP_SELECT.toLowerCase().replace(" ", "")
def gitRepo = ""
def dockerRegistry = ""
def helmName = ""
def projectConfig
def pipelinePath = "sample-pipeline"

node("general-pipeline") {
  container("ubuntu") {
    stage("Checkout pipeline project") {
      checkout scm
    }

    stage("Read yaml config") {
      projectConfig = readYaml(file: "${pipelinePath}/pipeline-config.yaml")
    }

    stage("Select config") {
      def selected = projectConfig.projectConfigs[SELECT_STUPID_PROJECT]

      gitRepo = selected.gitRepo
      dockerRegistry = selected.dockerRegistry
      helmName = selected.helmName
    }
  }

  container("kaniko"){
    stage("Build image") {
      if(buildStepSelected.contains("builddocker")) {
        sh """
          /kaniko/executor \
            --context=git://github.com/${gitRepo}#refs/heads/main \
            --dockerfile=Dockerfile \
            --destination=careromspersonal/${dockerRegistry}:latest
        """
      } else {
        echo "Skip docker build step."
      }
    }
  }

  container("helm") {
    if(buildStepSelected.contains("helmdeploy")) {
      stage("Check file") {
        sh "ls"
      }

      stage("Helm deploy") {
        sh "helm upgrade ${helmName} --install --namespace default ./${pipelinePath}/helm --debug"
      }
    } else {
      echo "Skip Helm deploy step."
    }
  }
}